version = 1

[git]
default_branch = "main"
short_tags = "imjlk/connector-for-newspack-newsletters-and-listmonk"

[github]
repository = "imjlk/newspack-listmonk-connector"

[changesets]
tags = ["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security"]

[changelog]
show_commit_hash = true
show_acknowledgments = true
show_release_date = true
release_date_format = "%Y-%m-%d"
release_date_timezone = "Asia/Seoul"

[packages]
ignore_unpublished = true
