import fs from 'node:fs';
import { spawnSync } from 'node:child_process';

import { loadDotEnv } from './smoke-lib.mjs';

const composeFile = 'docker-compose.listmonk.yml';
const generatedEnvFile = '.listmonk.env';
const dockerBin = process.platform === 'win32' ? 'docker.exe' : 'docker';

loadDotEnv();

const hostPort = process.env.LISTMONK_DOCKER_PORT || '9000';
const browserBaseUrl = `http://127.0.0.1:${hostPort}`;
const wpContainerBaseUrl =
	process.env.LISTMONK_WP_BASE_URL || `http://host.docker.internal:${hostPort}`;
const apiUser = process.env.LISTMONK_ADMIN_API_USER || 'wp_typia_smoke';
const defaultListIds = process.env.LISTMONK_DEFAULT_LIST_IDS || '1';
const fromEmail = process.env.LISTMONK_FROM_EMAIL || 'Smoke Test <smoke@example.com>';

const command = process.argv[2] || 'start';

function runDocker(args, options = {}) {
	const result = spawnSync(dockerBin, args, {
		cwd: process.cwd(),
		encoding: 'utf8',
		input: options.input,
		stdio: ['pipe', 'pipe', 'pipe'],
	});

	if (result.error) {
		throw result.error;
	}

	if (!options.allowFailure && result.status !== 0) {
		throw new Error(
			[
				`Docker command failed: docker ${args.join(' ')}`,
				result.stdout.trim(),
				result.stderr.trim(),
			]
				.filter(Boolean)
				.join('\n')
		);
	}

	return result;
}

function compose(args, options = {}) {
	return runDocker(['compose', '-f', composeFile, ...args], options);
}

function printOutput(result) {
	const output = [result.stdout.trim(), result.stderr.trim()]
		.filter(Boolean)
		.join('\n');
	if (output) {
		console.log(output);
	}
}

function readGeneratedToken() {
	if (!fs.existsSync(generatedEnvFile)) {
		return '';
	}

	const content = fs.readFileSync(generatedEnvFile, 'utf8');
	const match = content.match(/^LISTMONK_API_TOKEN=(?:"([^"]+)"|(.+))$/m);
	return match ? (match[1] || match[2] || '').trim() : '';
}

function extractToken(logs) {
	const matches = [...logs.matchAll(/LISTMONK_ADMIN_API_TOKEN="?([^"\s]+)"?/g)];
	if (!matches.length) {
		return '';
	}

	return matches[matches.length - 1][1];
}

function getLogs() {
	return compose(['logs', '--no-color', 'listmonk'], { allowFailure: true }).stdout;
}

async function waitForHttp(url) {
	const deadline = Date.now() + 120_000;
	let lastError = null;

	while (Date.now() < deadline) {
		try {
			const response = await fetch(url, { redirect: 'manual' });
			if (response.status > 0 && response.status < 500) {
				return;
			}
			lastError = new Error(`HTTP ${response.status}`);
		} catch (error) {
			lastError = error;
		}

		await new Promise((resolve) => setTimeout(resolve, 2000));
	}

	throw new Error(`Timed out waiting for ${url}: ${lastError?.message || 'no response'}`);
}

async function waitForToken() {
	const deadline = Date.now() + 120_000;
	let token = readGeneratedToken();

	while (!token && Date.now() < deadline) {
		token = extractToken(getLogs());
		if (token) {
			return token;
		}
		await new Promise((resolve) => setTimeout(resolve, 2000));
	}

	if (!token) {
		throw new Error(
			[
				'Unable to find LISTMONK_ADMIN_API_TOKEN in Listmonk logs.',
				'If this database was created before API-token capture was added, run pnpm run listmonk:destroy and then pnpm run listmonk:start.',
			].join(' ')
		);
	}

	return token;
}

async function waitForApi(token) {
	const deadline = Date.now() + 120_000;
	let lastError = null;

	while (Date.now() < deadline) {
		try {
			const response = await fetch(`${browserBaseUrl}/api/lists?per_page=1`, {
				headers: {
					Authorization: `token ${apiUser}:${token}`,
				},
			});
			if (response.ok) {
				return;
			}
			lastError = new Error(`HTTP ${response.status}: ${await response.text()}`);
		} catch (error) {
			lastError = error;
		}

		await new Promise((resolve) => setTimeout(resolve, 2000));
	}

	throw new Error(
		`Timed out waiting for authenticated Listmonk API: ${lastError?.message || 'no response'}`
	);
}

function quoteEnv(value) {
	return `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function writeGeneratedEnv(token) {
	const content = [
		'# Generated by pnpm run listmonk:start.',
		'# WordPress runs inside wp-env, so the API URL uses host.docker.internal.',
		`LISTMONK_BASE_URL=${wpContainerBaseUrl}`,
		`LISTMONK_API_USER=${apiUser}`,
		`LISTMONK_API_TOKEN=${quoteEnv(token)}`,
		`LISTMONK_DEFAULT_LIST_IDS=${defaultListIds}`,
		`LISTMONK_FROM_EMAIL=${quoteEnv(fromEmail)}`,
		'',
	].join('\n');

	fs.writeFileSync(generatedEnvFile, content, 'utf8');
}

async function start() {
	console.log('Starting local Listmonk with Docker Compose...');
	printOutput(compose(['up', '-d']));

	await waitForHttp(browserBaseUrl);
	const token = await waitForToken();
	writeGeneratedEnv(token);
	await waitForApi(token);

	console.log(`Local Listmonk is ready at ${browserBaseUrl}`);
	console.log(`Smoke credentials were written to ${generatedEnvFile}`);
}

async function writeEnv() {
	const token = await waitForToken();
	writeGeneratedEnv(token);
	console.log(`Smoke credentials were written to ${generatedEnvFile}`);
}

async function main() {
	if ('start' === command) {
		await start();
		return;
	}
	if ('env' === command) {
		await writeEnv();
		return;
	}
	if ('logs' === command) {
		printOutput(compose(['logs', '--no-color', 'listmonk']));
		return;
	}
	if ('stop' === command) {
		printOutput(compose(['down']));
		return;
	}
	if ('destroy' === command) {
		printOutput(compose(['down', '-v']));
		if (fs.existsSync(generatedEnvFile)) {
			fs.unlinkSync(generatedEnvFile);
		}
		return;
	}

	throw new Error(`Unknown command: ${command}`);
}

main().catch((error) => {
	console.error(error.message);
	process.exit(1);
});
